CREATE TABLE IF NOT EXISTS users (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    firebase_uid    VARCHAR(255),
    name            VARCHAR(255) NOT NULL,
    title           VARCHAR(255),
    gender          VARCHAR(255),
    dob             VARCHAR(255),
    mobile_number   VARCHAR(255),
    email           VARCHAR(255),
    role            VARCHAR(50)  NOT NULL DEFAULT 'CUSTOMER',
    status          VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
    mobile_verified TINYINT(1)   NOT NULL DEFAULT 1,
    email_verified  TINYINT(1)   NOT NULL DEFAULT 0,
    active          TINYINT(1)   NOT NULL DEFAULT 1,
    created_at      DATETIME(6),
    updated_at      DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_firebase_uid  (firebase_uid),
    UNIQUE KEY uk_mobile_number (mobile_number),
    UNIQUE KEY uk_email         (email),
    INDEX idx_user_mobile (mobile_number),
    INDEX idx_user_email  (email),
    INDEX idx_user_name   (name),
    INDEX idx_user_status (status),
    INDEX idx_user_role   (role)
);
